CREATE VIEW gold.dim_customer AS
SELECT
	ROW_NUMBER() OVER(ORDER BY cst_id) AS customer_key,
	ci.cst_id AS customer_id,
	ci.cst_key AS customer_number,
	ci.cst_firstname AS first_name,
	ci.cst_lastname AS last_name,
	la.cntry AS country,
	ci.cst_marital_status AS marital_status,
	CASE 
		WHEN ci.cst_gndr != 'n/a' THEN ci.cst_gndr -- crm is the master for gender information
		ELSE COALESCE(ca.gen, 'n/a') -- grab it from the erp
	END gender,
	ca.bdate AS birth_date,
	ci.cst_create_date AS create_date
FROM silver.crm_cust_info ci
LEFT JOIN silver.erp_cust_az12 ca
	ON ci.cst_key = ca.cid
LEFT JOIN silver.erp_loc_a101 la
	ON ci.cst_key = la.cid


/*
	READ THIS FOR BETTER UNDERSTANDING:

	First selecting all the data from the crm_cust_info which is the master table, then joining data with the erp tables which contain customer information.
	Here we will try avoid INNER JOIN because the other table might not contain full data and by INNER JOIN we will be losing the data. So the 
	master table shall always be joined using LEFT JOIN. By joining the 3 tables we will get all the customer information from the given source systems.
	If you see many nulls in the new joined columns then your joins might be wrong.
	If your first table has no duplicated, after doing multiple joins you might start getting duplicates because the relationship between those tables are not One
	to one, it is one to many relationship. At this stage check for duplicates by using group by and count > 1

	Data Integration:
		It is used to get more rich data into data warehouse
		Now we have two gender tables we will check for data issues in it. When we run this query we will see the following scenerios
		1. LHS != RHS : In this case we will refer to the experts and ask them which table is the master table, after knowing it the priority goes to the 
			value coming from the master table
		2. One of them is NULL: You might be wondering where the null came from we cleaned all the data in the silver layer. Ths null tells us that there are some
			entries in the other table which are not present in the master table.
		
			SELECT DISTINCT
				ci.cst_gndr,
				ca.gen
			FROM silver.crm_cust_info ci
			LEFT JOIN silver.erp_cust_az12 ca
				ON ci.cst_key = ca.cid
			LEFT JOIN silver.erp_loc_a101 la
				ON ci.cst_key = la.cid
			ORDER BY 1,2


	Now define it is a fact table or dimension table:
		This table contains description and informations so it is a Dimension. Whenever you have a Dimension table you always need a Primary Key. You 
		must not depend on already present PRIMARY KEYS as sometimes they are not avilable. You should generate your own Primary key in you Data Warehouse 
		and those Primary KEYS are called SURROGATE KEYS
	SURROGATE KEYS:
		System generated unique identifiers assigned to each record to make the record unique in a table. They are meaningless. They are only used to make 
		the record unique. They can be generated by either manipulating the DDL or by using the Window Function ROW_NUMBER().
		
	Object Creation
		As we have already decided all the objects in the Gold layer will be virtual one. So we will be making views

	Now go and check the quality of this new object
*/